import type { Metadata } from "next";
import "./globals.css";
// import localFont from "next/font/local";
import Footer from "./components/generic/Footer";
import FadeInUp from "./components/animations/FadeInUp";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-[Futura] antialiased`}>
        {children}
        <FadeInUp>
          <Footer />
        </FadeInUp>
      </body>
    </html>
  );
}
